name: Pull request checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 20.16.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm i
      - name: Run lint
        run: pnpm lint:all
  cancel_merge:
    runs-on: ubuntu-latest
    needs: [run_checks]
    steps:
      - name: Cancel the merger if the checks fail
        if: failure()
        run: |
          echo "Checks failed. Cancelling the merge."
          exit 1
